export const LOAD_USER = 'LOAD_USER';
export const UNLOAD_USER = 'UNLOAD_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const ADD_TO_CREATED_POOLS = 'ADD_TO_CREATED_POOLS';
export const REMOVE_FROM_CREATED_POOLS = 'REMOVE_FROM_CREATED_POOLS';
export const FOLLOW_POOL = 'FOLLOW_POOL';
export const UNFOLLOW_POOL = 'UNFOLLOW_POOL';
export const LOAD_POOL = 'LOAD_POOL';
export const UNLOAD_POOL = 'UNLOAD_POOL';
export const ADD_FOLLOWER = 'ADD_FOLLOWER';
export const REMOVE_FOLLOWER = 'REMOVE_FOLLOWER';
export const ADD_VOTE = 'ADD_VOTE';
export const SCHEDULE_POOL_FOR_DELETE = 'SCHEDULE_POOL_FOR_DELETE';

