export const LOAD_USER = 'LOAD_USER';
export const UNLOAD_USER = 'UNLOAD_USER';
export const ADD_TO_CREATED_POOLS = 'ADD_TO_CREATED_POOLS';
export const REMOVE_FROM_CREATED_POOLS = 'REMOVE_FROM_CREATED_POOLS';
